### ISSUE TITLE
25ns data and preparation for MiniAODv2

### ISSUE THREAD

**Issue by kreczko** [BristolTopGroup/NTupleProduction#165]
This issue is a long one but can be done in several separate pull request.
The items are:
 - [x] switch to ```CMSSW_7_4_12``` or newer (#168)
 - [x] implement global tags (```74X_mcRun2_asymptotic_v2``` for 25ns MC, ```74X_mcRun2_startup_v2``` for 50ns MC and ```74X_dataRun2_v2``` for data (both 25 and 50s) (#172)
 - [x] change ```met.uncorrectedPt()``` to ```met.uncorPt()```
 - [x] drop custom calculation of METNoHF and use ~~```slimmedMETNoHF```~~ ```slimmedMETs``` instead (#172)
 - [x] add the following Electron VIDs: ```Spring15_25ns_V1```, ```Spring15_50ns_V1```, ```mvaElectronID_Spring15_25ns_nonTrig_V1``` (#171)
 - [x] adjust PU information (```addPileupInfo``` &#8594; ```slimmedAddPileupInfo```) (#173)
